### ISSUE TITLE
Open question: When does it make sense to add things to the "recent songs" page

### ISSUE THREAD

**Issue by skywalkerdude** [HymnalDreamTeam/Hymns-iOS#201]
Currently, whenever we load a song, it gets added to "Recent songs".

But as we add languages and alternate tunes, there is the risk of polluting recent songs with many variations of the same song. For example: 
![Simulator Screen Shot - iPhone 8 - 2020-05-27 at 19 03 59](https://user-images.githubusercontent.com/1427524/83090143-f107cb80-a04c-11ea-9f72-d798e9305c60.png)

So the question here is, do you think it makes sense, when the user goes to a different language of a song, to add the different language to the recent songs, or does it only make sense to add it when the user actively searches for it?

**Comment by finben** [comment]
Personally, It think it should be off of active search only. You would have to have typed that language in and selected it to have that language hymn appear here.

**Comment by Emyeh** [comment]
I agree it should be based on what they searched and not reflect changes they made within the hymn. This also simplifies the experience and won't cause confusion about that section. It clearer that what appears there is what I searched for in 'Search' and tapped into.

If we think calling out alternative tunes is important, the ideal way would be to have a visual indicator upfront next to the title. Then it doesn't look like a duplicate bug in Recent Hymns. I personally think that's not too important to have, because it's easy to switch between tunes.
