### ISSUE TITLE
'Cancel' and 'Add' button should be below the tags created

### ISSUE THREAD

**Issue by Emyeh** [HymnalDreamTeam/Hymns-iOS#291]
![IMG_7557](https://user-images.githubusercontent.com/26554065/84587279-a3bc8580-add2-11ea-8d1e-c66933bc7aba.PNG)

Also thinking after a user adds a tab should we change the 'cancel' button to 'done'. Or place 'add' somewhere else. It might be confusing since 'cancel' doesn't get rid of the tags added. I'll need to revisit the CTAs here.

**Comment by skywalkerdude** [comment]
Hmm, it doesn't seem to resize correctly either. It seems to look like this after resizing from extra large back to normal: 
![Simulator Screen Shot - iPhone 8 - 2020-06-14 at 13 48 26](https://user-images.githubusercontent.com/1427524/84603767-c340c600-ae45-11ea-9708-5e98d9dca52d.png)

**Comment by skywalkerdude** [comment]
@Emyeh is it a big deal to you that the buttons are above the tag list instead of below? There's a limitation with the iOS UI framework we are using that causes the add/cancel button to be docked at the very bottom of the screen, so there's a huge gap in the middle. I was hoping to ship with it looking like this for now and hopefully at WWDC 20 they'll give us some solutions.

**Comment by finben** [comment]
@skywalkerdude  😂 Lol! I just took a look at this. Your geometry reader taking up to much space xD

**Comment by Emyeh** [comment]
Forget what I said about changing the button from 'Cancel' to 'Done' after adding a tag. It'll be clearer just to rename 'Cancel' to 'Close'.
